### ISSUE TITLE
Latest type definition breaks typescript compilation

### ISSUE THREAD

**Issue by pduchesne** [JMPerez/spotify-web-api-js#121]
My typescript code uses the api as follows : 
```
import * as SpotifyWebApi from 'spotify-web-api-js';

let spotifyApi: SpotifyWebApi.SpotifyWebApiJs;
```

This works fine with 1.1.0 .
Since 1.1.1 , this fails with `Namespace '".../spotify-web-api"' has no exported member 'SpotifyWebApiJs'` .

I could not find a way to work with the new type file.

**Comment by JMPerez** [comment]
That's interesting. The latest change related to that was https://github.com/JMPerez/spotify-web-api-js/pull/44, which shipped in 1.1.0.

I'm myself not that familiar with Typescript so I would appreciate if someone can jump in and help debugging this issue. Maybe @amelialaundy can help out?

**Comment by amelialaundy** [comment]
Hey @pduchesne I have the following:
```
import SpotifyWebApi from 'spotify-web-api-js'
export class Spotify {
	private client: SpotifyWebApi.SpotifyWebApiJs;
	constructor(token: string) {
		this.client = new SpotifyWebApi();
		this.client.setAccessToken(token);
	}
```

That should work for you.

I think I made those type changes in 1.1.0, and sounds like what you are saying is they are breaking changes so I'll take a look.

**Comment by csantiago132** [comment]
@JMPerez @amelialaundy  @pduchesne in my app, im using it like this (this is in a saga btw but should not matter) 
```typescript
import SpotifyWebApi from 'spotify-web-api-js';

const spotifyApi = new SpotifyWebApi();
```

whole file looks like this:
```typescript
import { call, put, takeLatest, fork } from 'redux-saga/effects';
import SpotifyWebApi from 'spotify-web-api-js';
import ActionTypes from './constants';
import * as Actions from './actions';

const spotifyApi = new SpotifyWebApi();

/**
 * @generator
 * @remarks working saga in charge of getting the albums data from Spotify
 *
 */
export function* getAlbumCatalogSaga() {
  const token = sessionStorage.getItem('react-spotify-access-token');
  spotifyApi.setAccessToken(`${token}`);

  /**
   * @function
   * @remarks calls the spotify endpoint that has the user's albums
   *
   * @returns Promise
   */
  const getSpotifyPlaylists = () =>
    spotifyApi
      .getMySavedAlbums()
      .then((response) => response)
      .catch((error) => new Error(`${error}`));

  try {
    const getData = yield call(getSpotifyPlaylists);
    yield put(Actions.fetchSpotifyAlbumSuccess(getData));
  } catch (error) {
    yield put(Actions.fetchSpotifyAlbumError(error.message));
  }
}

/**
 * @generator
 * @remarks root saga manages watcher lifecycle of getAlbumCatalogSaga()
 */
export function* albumCatalogSaga() {
  /**
   * Calls for authorization from Spotify every time it is called,
   * by using `takeLatest` only the result of the latest API call is applied.
   * It will be cancelled automatically on component unmount
   */
  yield takeLatest(ActionTypes.SPOTIFY_ALBUM_IS_LOADING, getAlbumCatalogSaga);
}

/**
 * export for saga registry
 */
export const saga = [fork(albumCatalogSaga)];
```

**Comment by bmitchinson** [comment]
Having a similar issue, maybe I'm missing something obvious?

```
import SpotifyWebApi from 'spotify-web-api-js';
const spotifyApi = new SpotifyWebApi();

spotifyApi.setAccessToken('xxxxx');
```
results in 
```
TypeError: spotify_web_api_js_1.default is not a constructor
    at Object.<anonymous> (/Users/bmitchinson/Playlists/platformScripts/spotify/spotifyToFirestore.ts:5:20)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/Users/bmitchinson/.nvm/versions/node/v8.11.1/lib/node_modules/ts-node/src/index.ts:473:23)
```

**Comment by bmitchinson** [comment]
I'm a loser, reminder that this library is for web, not [for node](https://github.com/thelinmichael/spotify-web-api-node).

Was able to get around that error above by messing around with the transpilled js, and removing `default` from the constructor call. Obviously that lead to the realization that I should have just read the readme 🥇

**Comment by JMPerez** [comment]
Closed with commit https://github.com/JMPerez/spotify-web-api-js/commit/1487329717fc12665bd9b983b71040609bdb4069
